---
collections:
  - ansible.posix
  - community.postgresql
  - community.general
roles:
  - dimmaryanto93.keepalived
  - dimmaryanto93.ha_proxy
  - dimmaryanto93.postgres_community
  - dimMaryanto93.nutanix_db-patch-os
